### PR TITLE
Release of v5.1.1

### PR DESCRIPTION
**Pull request by lschreck-mdsol**
This PR contains all updates, changes and fixes since v5.0.0.

@mdsol/architecture-enablement @mdsol/team-51 @mdsol/libraries_dotnet please review/merge - thanks!

### CODE REVIEW

**Comment by jfeltesse-mdsol** [comment]
all changes previously reviewed in their respective PRs, right?

**Comment by lschreck-mdsol** [comment]
> all changes previously reviewed in their respective PRs, right?

Yes, this is only for moving the done code to master (for the release).

**Review by jfeltesse-mdsol — APPROVED** [review]

**Comment by jfeltesse-mdsol** [comment]
I'd merge but my rank is too low... 😭 

Screen Shot 2021-02-24 at 17 46 34

**Comment by lschreck-mdsol** [comment]
What? I've never seen this before - now I am wondering how/who is this configured to allow the merge...

**Comment by bvillanueva-mdsol** [comment]
Im not sure why I have this magic button, but will click it! 
image

**Pull request merged**
