### PR TITLE
[MCC-270638] Move NETStandard.Library dependency from root dependencies node to under netstandard1.4

### PR DESCRIPTION
**Pull request by hkurniawan-mdsol**
This to avoid legacy .NET project to download unnecessary NETStandard libraries.

@lschreck-mdsol, @bvillanueva-mdsol, @kenyamat please review and merge if okay.

FYI
@cabbott

### CODE REVIEW

**Comment by lschreck-mdsol** [comment]
Looks good, @hkurniawan-mdsol can you bump up the version numbers to 2.1.1?

**Comment by hkurniawan-mdsol** [comment]
@lschreck-mdsol, ah yes, we released 2.1.0 already.
Version bumped!

**Comment by bvillanueva-mdsol** [comment]
I see. I tried using the current mauth in archon client and got lots of nugets that looks like for dotnet core. 
Thanks!
LGTM too

**Comment by lschreck-mdsol** [comment]
Then we are ready to merge!

**Pull request merged**
