### PR TITLE
[MCC-771288] Add Workflow for Publishing the Packages

### PR DESCRIPTION
**Pull request by lschreck-mdsol**
This PR adds a new workflow to publish the packages to our Artifactory feed.

@mdsol/enablement-dotnet Please review and merge - thanks!

### CODE REVIEW

**Comment by jfeltesse-mdsol** [comment]
what's the trigger? every time there's a push to develop? preferrably, publishing runs only upon tagging (a version can be made of several PRs)

**Comment by lschreck-mdsol** [comment]
> what's the trigger? every time there's a push to develop? preferrably, publishing runs only upon tagging (a version can be made of several PRs)

Yes, currently if `develop` gets a merge - I think we can follow the "one PR - one version" cadence for libraries - especially because I don't think we have any big feature release in the future (or if we have, we can change the configuration of the publish workflow).

**Comment by jfeltesse-mdsol** [comment]
Thanks. Also, this is going to be very convenient to re-tag the old releases after 5.0.0 so they get published now. Will do once this PR is in!

**Comment by lschreck-mdsol** [comment]
Ok, and I merged one PR which removes a dependency so I bumped the version number here.

**Review by jfeltesse-mdsol — APPROVED** [review]

**Comment by jfeltesse-mdsol** [comment]
Please make a develop -> master PR and then we can tag off master.

About my previous comment, alas, that won't apply since old commits wouldn't yet feature the GHA test/publish flow... 🤦

**Pull request merged**
