### PR TITLE
[MCC-760494] Remove obsolete build scripts

### PR DESCRIPTION
**Pull request by lschreck-mdsol**
As the title says - we already retired the AppVeyor build and MyGet, so these artifacts should be removed from the repository.

@mdsol/architecture-enablement please review and merge - after that I will open another PR to merge to master as well. Thanks!

### CODE REVIEW

**Comment by prajon84** [comment]
@lschreck-mdsol : Does that mean that we will create separate travis build to push to nuget later ?

**Comment by lschreck-mdsol** [comment]
> @lschreck-mdsol : Does that mean that we will create separate travis build to push to nuget later ?

Yes, we already planning to configure Travis we just need some administrative changes before.

**Comment by jfeltesse-mdsol** [comment]
I guess we can trash the deployment part that wasn't working anymore anyway but how about using GHA to at least run the tests?
We can cover the deployment of packages upon tagging at a later time.

**Comment by lschreck-mdsol** [comment]
> edit: to clarify I'm advocating GHA and not travis because Travis CI is not OSS friendly anymore 😢

Ok, that's a new information - I thought we can run this project on Travis CI just like we did it on AppVeyor. But GHA sounds like a good idea, let me see if I can come up with something.

**Comment by jfeltesse-mdsol** [comment]
https://github.com/openzipkin/zipkin-ruby/pull/180#issuecomment-735598960

https://travis-ci.community/t/intending-to-use-travis-for-a-foss-project-forget-it/11406

🤦

**Review by prajon84 — APPROVED** [review]

**Review by jfeltesse-mdsol — APPROVED** [review]

**Pull request merged**
